insert into bank (bank_name) values ('EL CREDITO HIPOTECARIO NACIONAL DE GUATEMALA');
insert into bank (bank_name) values ('INMOBILIARIO, S. A.');
insert into bank (bank_name) values ('DE LOS TRABAJADORES');
insert into bank (bank_name) values ('INDUSTRIAL, S. A.');
insert into bank (bank_name) values ('DE DESARROLLO RURAL, S. A.');
insert into bank (bank_name) values ('INTERNACIONAL, S. A.');
insert into bank (bank_name) values ('CITIBANK, N.A., SUCURSAL GUATEMALA');
insert into bank (bank_name) values ('VIVIBANCO, S. A.');
insert into bank (bank_name) values ('FICOHSA GUATEMALA, S. A.');
insert into bank (bank_name) values ('PROMERICA, S. A.');
insert into bank (bank_name) values ('DE ANTIGUA, S. A.');
insert into bank (bank_name) values ('DE AMERICA CENTRAL, S. A.');
insert into bank (bank_name) values ('AGROMERCANTIL DE GUATEMALA, S. A.');
insert into bank (bank_name) values ('G&T CONTINENTAL, S. A.');
insert into bank (bank_name) values ('AZTECA DE GUATEMALA, S. A.');
insert into bank (bank_name) values ('INV, S. A.');
insert into bank (bank_name) values ('CREDICORP, S. A.');